#!/bin/bash

set -ex

sudo docker build -t mattermost-plugin-bbb-builder .
sudo docker run --rm -it \
  -v $(pwd):/go/src/github.com/blindsidenetworks/mattermost-plugin-bigbluebutton/ \
  -w /go/src/github.com/blindsidenetworks/mattermost-plugin-bigbluebutton/ \
  mattermost-plugin-bbb-builder make "$@"
