id: bigbluebutton
name: BigBlueButton
backend:
    executable: server/plugin.exe
webapp:
    bundle_path: webapp/bigbluebutton_bundle.js
settings_schema:
  settings:
  - key: BASE_URL
    display_name: BigBlueButton Server URL
    type: text
    default: http://test-install.blindsidenetworks.com/bigbluebutton/api
    help_text: >
      The URL of your BigBlueButton server. Ends with /bigbluebutton/api
      Default: `http://test-install.blindsidenetworks.com/bigbluebutton/api`.
  - key: SALT
    display_name: Secret
    type: text
    default: 8cd8ef52e8e101574e400365b55e11a6
    help_text: >
      The secret you generated to securely connect to your BigBlueButton server. Default for
      test-install: 8cd8ef52e8e101574e400365b55e11a6
  - key: CallBack_URL
    display_name: Site URL
    type: text
    help_text: >
      Your mattermost server URL, ie: https://mycompany.mattermost.com
  footer: All forms must be filled or pluging will fail to activate. Deactivate and reactivate your plugin when changing to a new configuration. Don't worry, no data will be lost
