id: bigbluebutton
name: BigBlueButton
backend:
    executable: server/plugin.exe
webapp:
    bundle_path: /static/bigbluebutton_bundle.js
settings_schema:
  settings:
  - key: BASE_URL
    display_name: BigBlueButton Server URL
    type: text
    default: http://test-install.blindsidenetworks.com/bigbluebutton/api
    help_text: Enter the address of your BigBlueButton server
  - key: SALT
    display_name: Secret
    type: text
    default: 8cd8ef52e8e101574e400365b55e11a6
    help_text: The secret you generated to securely connect to your BigBlueButton
  - key: CallBack_URL
    display_name: Site URL
    type: text
    help_text: Your mattermost URL, ie:mycompany.mattermost.com
  footer: Deactivate and reactivate your plugin when changing to a new configuration. Don't worry, no data will be lost
