#!/bin/bash

set -ex

podman build -t mattermost-plugin-bbb-builder .
podman run --rm -it \
  -v $(pwd):/go/src/github.com/blindsidenetworks/mattermost-plugin-bigbluebutton/ \
  -w /go/src/github.com/blindsidenetworks/mattermost-plugin-bigbluebutton/ \
  mattermost-plugin-bbb-builder make "$@"
